version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack Edge Port
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s http://localhost:4566/_localstack/health | jq -e '.services.dynamodb == \"running\"'"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - parking-network
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - parking-network
  car-registration:
    image: digital-parking-system-registration:latest
    container_name: car-registration
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      localstack:
        condition: service_healthy
    restart: always
    networks:
      - parking-network
  car-process:
    image: digital-parking-system-process:latest
    container_name: car-process
    ports:
      - "8082:8082"
    depends_on:
      car-registration:
        condition: service_healthy
    restart: always
    networks:
      - parking-network
networks:
  parking-network:
    driver: bridge
